# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
resources:
  containers:
  - container: gcc49
    image: 'tmbgreaves/devito-gcc-4.9'

jobs:
- job: Container_Build
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      gcc4:
        gcc.version: '4.9'
      gcc5:
        gcc.version: '5'
    maxParallel: 2

  variables:
    imageName: devito-gcc
  steps:
  - script: |
      docker build -f Dockerfile.azurepipeline -t $(dockerId)/$(imageName)-$(gcc.version):$(Build.BuildId) --build-arg gccvers=$(gcc.version) .
      docker tag $(dockerId)/$(imageName)-$(gcc.version):$(Build.BuildId) $(dockerId)/$(imageName)-$(gcc.version):latest
      docker login -u $(dockerId) -p $(dockerPassword)
      docker push $(dockerId)/$(imageName)-$(gcc.version):$(Build.BuildId)
      docker push $(dockerId)/$(imageName)-$(gcc.version):latest

- job: Testing
  dependsOn: Container_Build
  condition: succeeded('Container_Build')
  pool:
    vmImage: 'Ubuntu 16.04'
  container: gcc49
  steps:
  - script: git clean -fxd
    displayName: 'Restore checkout to clean state'
  - script: python setup.py install
    displayName: 'Install'
  - script: bin/flake8 --builtins=ArgumentError .
    displayName: 'Run flake8'
  - script: python setup.py test
    displayName: 'Run tests'
